# Generated by Django 6.0 on 2025-12-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_chunkembedding_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='modality',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10),
        ),
    ]
